### ISSUE TITLE
The registered cities can be repeated in the register.

### ISSUE THREAD

**Issue by buhlerax** [alexloehner/linuxcounter.new#17]
The registered cities can be repeated in the register.
See that there are three cities Curitiba in Brazil.
What if I want new registering will put one more.
It would be ideal to join the repeated cities in a single record.
And do not allow the registration of a city that already exists for the same country and state.
It would also be nice to edit the registered city data.
For example one of Curitiba registers this with the wrong coordinates and without stat or region.

**Comment by alexloehner** [comment]
Thanks for this report... I'll try to fix this in the next days.

**Comment by alexloehner** [comment]
This is fixed since yesterday. creating a new city with same name in the same country is no longer allowed. I know that there are many cities with the same name in one single country, but the application can not decide if it is a duplicate or not, since the region or the coordinates may be empty in already existent cities.

I've also created some management stuff like editing city data and merging cities to one single new city. This is only for ROLE_MANAGER only (for now). Maybe I'l make this publicy available soon, as there may be noone who wants to help me as a city manager or something.

**Comment by buhlerax** [comment]
Thank you
