### ISSUE TITLE
No account button on api site

### ISSUE THREAD

**Issue by krichter722** [alexloehner/linuxcounter.new#28]
After opening http://api.linuxcounter.net/ with the `API` on the top navigation bar, there's no account button, like in all other sites which can be opened with the button in the top navigation bar.

**Comment by alexloehner** [comment]
@krichter722  Since the API resides on an own (sub-)domain, the login is not guilty for the API documentation and thus I can not show the "Account" dropdown with the links to your profile and such, because you are not logged in on that subdomain.

Since this just simply is a one page documentation of the API, I think this is not tragically.

Best regards
Alex
