### ISSUE TITLE
Loicalization incomplete

### ISSUE THREAD

**Issue by lhitc** [alexloehner/linuxcounter.new#3]
In the "Account" Submenu 2 points are in English when Herman language is selected

**Comment by alexloehner** [comment]
Hey, thanks for your report. The localization is of course not completed yet and will take seveal months, maybe years, until it is completed, because this needs to be done by the community.

Actually the whole application is completly in english and only some small, several parts are correctly translated to other languages.

This is of course not a bug, but a feature request. 

I'll provide a possibility for the users/community to translate the application in their native language, but this will also need some time, as this is very low prioritized.

**Comment by lhitc** [comment]
Well, if German language is a chooseable option, it is a bug in an existing feature ;-)
However for sure a very low prioritized one.

Unfortunately I'm out when it comes to other languages than German or English and I suppose your German is good enough. However if you need a reviewer for the German localization, let me know.

**Comment by alexloehner** [comment]
Since I'm a native german speaker by myself, I suppose my german as god enough too.  :-)
But I'm always glad about help!

So, when the translation application is finished and the translations can then be done by the user themselfes, it would be fine if you can look over the german translations.

But as I said, this is one of the lowest proiritized things at all. First the statistics has to get finished and the update script. ;-)

**Comment by alexloehner** [comment]
So, the community translation tool is implemented. See here: http://www.linuxcounter.net/news/5
